config/routes.rb
Rails.application.routes.draw do
  resources :makes do
    resources :models
  end

end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :models, dependent: :destroy
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :make
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
      @models = @make.models
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name)
    end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_make
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = @make.models
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = @make.models.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = @make.models.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to [@make,@model], notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to [@make,@model], notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to make_models_url(@make), notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_model
      @model = @make.models.find(params[:id])
    end

    def set_make 
      @make = Make.find(params[:make_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:make_id, :model)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tuauto
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = navbar fixed: :top do
      = navbar_collapse do
        = navbar_group do
          = navbar_item 'Marcas', makes_path

    .container
      .row
        .span12
          = render_breadcrumbs
          = bootstrap_flash
          = yield

app/views/makes/_form.html.haml
= form_for(@make) do |f|
  - if @make.errors.any?
    #error_explanation
      %h2
        = pluralize(@make.errors.count, "error")
        prohibited this make from being saved:
      %ul
        - @make.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/makes/edit.html.haml
%h1 Editing Make
= render 'form'
= link_to 'Show', @make
|
= link_to 'Back', makes_path

app/views/makes/index.html.haml
%p#notice= notice
%h1 Listado de Marcas
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @makes.each do |make|
      %tr
        %td= make.name
        %td= link_to 'Show', make
        %td= link_to 'Edit', edit_make_path(make)
        %td= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Make', new_make_path

app/views/makes/new.html.haml
%h1 New Make
= render 'form'
= link_to 'Back', makes_path

app/views/makes/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @make.name
= link_to 'Edit', edit_make_path(@make)
|
= link_to 'Back', makes_path
= render 'models/index'

app/views/models/_form.html.haml
= simple_form_for([@make,@model]) do |f|
  - if @model.errors.any?
    #error_explanation
      %h2
        = pluralize(@model.errors.count, "error")
        prohibited this model from being saved:
      %ul
        - @model.errors.full_messages.each do |message|
          %li= message
  .field
    = f.input :model
  .actions
    = f.submit class: 'btn btn-default' 

app/views/models/_index.html.haml
%table
  %thead
    %tr
      %th Make
      %th Model
      %th{:colspan => "3"}
  %tbody
    - @models.each do |model|
      %tr
        %td= model.make.try(:name)
        %td= model.model
        %td= link_to 'Show', make_model_path(@make,model)
        %td= link_to 'Edit', edit_make_model_path(@make,model)
        %td= link_to 'Destroy',make_model_path(@make,model) , method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Model', new_make_model_path(@make)

app/views/models/edit.html.haml
%h1 Editing Model
= render 'form'
= link_to 'Show', make_model_path(@make, @model)
|
= link_to 'Back', make_models_path(@make)

app/views/models/index.html.haml
%p#notice= notice
%h1 Listing Models

= render 'index'

app/views/models/new.html.haml
%h1 New Model
= render 'form'
= link_to 'Back',  make_models_path(@make),	 class: 'btn btn-default'

app/views/models/show.html.haml
%p#notice= notice
%p
  %strong Make:
  = @model.make.try(:name)
%p
  %strong Model:
  = @model.model
= link_to 'Edit', edit_make_model_path(@make,@model)
|
= link_to 'Back', make_models_path(@make)